In [2]:
import pandas as pd

df_bolsa_jan = pd.read_csv("202501_NovoBolsaFamilia.csv", sep=';', encoding='latin1')
df_bolsa_fev = pd.read_csv("202502_NovoBolsaFamilia.csv", sep=';', encoding='latin1')

In [7]:
df_bolsa = pd.concat([df_bolsa_jan, df_bolsa_fev], ignore_index=True)

df_bolsa.shape

df_bolsa.tail(10)

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
40810983,202502,202502,TO,9643,XAMBIOA,***.699.321-**,2.379977e+10,WILLIAM ARAUJO DA COSTA BRITO,"750,00"
40810984,202502,202502,TO,9643,XAMBIOA,***.226.151-**,1.659589e+10,WILSON COSTA MENDES,"700,00"
40810985,202502,202502,TO,9643,XAMBIOA,***.008.261-**,1.665810e+10,WUELSA PEREIRA CRUZ,"800,00"
40810986,202502,202502,TO,9643,XAMBIOA,***.915.991-**,2.371195e+10,WYARA CARVALHO BARBOSA,"650,00"
40810987,202502,202502,TO,9643,XAMBIOA,NaN,1.626235e+10,YARA MARINHO DE CARVALHO,"750,00"
40810988,202502,202502,TO,9643,XAMBIOA,NaN,1.664089e+10,ZEIA DE SOUZA LUCIO,"750,00"
40810989,202502,202502,TO,9643,XAMBIOA,***.273.191-**,2.064488e+10,ZENILDE ALVES DOS SANTOS,"600,00"
40810990,202502,202502,TO,9643,XAMBIOA,NaN,1.905866e+10,ZENOLIA RAMOS DA SILVA CARVALHO,"600,00"
40810991,202502,202502,TO,9643,XAMBIOA,***.822.651-**,2.091926e+10,ZILMA ALVES DE BARROS,"600,00"
40810992,202502,202502,TO,9643,XAMBIOA,NaN,2.050120e+10,ZULEIDE DA SILVA E SILVA,"650,00"

In [ ]:
df_bolsa.to_parquet("bolsafamilia_202501_202502.parquet", index=False)

In [13]:
{
    "Shape": df_bolsapl.shape,
    "Head": df_bolsapl.head(10),
    "Tail": df_bolsapl.tail(10)
}

{'Shape': (40810993, 9),
 'Head': shape: (10, 9)
 ┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
 │ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
 │ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
 │ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
 │ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ f64        ┆ str       ┆ str       │
 │            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
 ╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
 │ 202501     ┆ 202308     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2.0644e10  ┆ FERNANDA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 6-**       ┆            ┆ RAMOS     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
 │ 202501     ┆ 202309     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2.0644e10  ┆ FERNANDA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 6-**       ┆            ┆ RAMOS     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
 │ 202501     ┆ 202310     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2.0644e10  ┆ FERNANDA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 6-**       ┆            ┆ RAMOS     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
 │ 202501     ┆ 202311     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2.0644e10  ┆ FERNANDA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 6-**       ┆            ┆ RAMOS     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
 │ 202501     ┆ 202312     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2.0644e10  ┆ FERNANDA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 6-**       ┆            ┆ RAMOS     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
 │ 202501     ┆ 202401     ┆ CE  ┆ 1389       ┆ … ┆ ***.854.49 ┆ 1.3024e10  ┆ IRENICE   ┆ 750,00    │
 │            ┆            ┆     ┆            ┆   ┆ 3-**       ┆            ┆ CAMELO    ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ VALETE    ┆           │
 │ 202501     ┆ 202401     ┆ PA  ┆ 479        ┆ … ┆ ***.868.79 ┆ 1.6025e10  ┆ ANTONIA   ┆ 600,00    │
 │            ┆            ┆     ┆            ┆   ┆ 2-**       ┆            ┆ ELIZANA   ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
 │ 202501     ┆ 202401     ┆ SP  ┆ 6313       ┆ … ┆ ***.972.79 ┆ 1.3310e10  ┆ DAMARIS   ┆ 800,00    │
 │            ┆            ┆     ┆            ┆   ┆ 8-**       ┆            ┆ DOS       ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
 │ 202501     ┆ 202401     ┆ SP  ┆ 6313       ┆ … ┆ ***.696.85 ┆ 2.0217e10  ┆ PRISCILA  ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 8-**       ┆            ┆ HELENA DE ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA      ┆           │
 │ 202501     ┆ 202401     ┆ SP  ┆ 6887       ┆ … ┆ ***.295.29 ┆ 1.6017e10  ┆ ERICA     ┆ 1010,00   │
 │            ┆            ┆     ┆            ┆   ┆ 8-**       ┆            ┆ CRISTINA  ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RIBEIRO   ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILV…  ┆           │
 └────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘,
 'Tail': shape: (10, 9)
 ┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
 │ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
 │ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
 │ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
 │ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ f64        ┆ str       ┆ str       │
 │            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
 ╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.699.32 ┆ 2.3800e10  ┆ WILLIAM   ┆ 750,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ ARAUJO DA ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COSTA     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BRITO     ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.226.15 ┆ 1.6596e10  ┆ WILSON    ┆ 700,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ COSTA     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MENDES    ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.008.26 ┆ 1.6658e10  ┆ WUELSA    ┆ 800,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ PEREIRA   ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CRUZ      ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.915.99 ┆ 2.3712e10  ┆ WYARA     ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ CARVALHO  ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BARBOSA   ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ null       ┆ 1.6262e10  ┆ YARA      ┆ 750,00    │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MARINHO   ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE        ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARVALHO  ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ null       ┆ 1.6641e10  ┆ ZEIA DE   ┆ 750,00    │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOUZA     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LUCIO     ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.273.19 ┆ 2.0645e10  ┆ ZENILDE   ┆ 600,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ ALVES DOS ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ null       ┆ 1.9059e10  ┆ ZENOLIA   ┆ 600,00    │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RAMOS DA  ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARVALH…  ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ ***.822.65 ┆ 2.0919e10  ┆ ZILMA     ┆ 600,00    │
 │            ┆            ┆     ┆            ┆   ┆ 1-**       ┆            ┆ ALVES DE  ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BARROS    ┆           │
 │ 202502     ┆ 202502     ┆ TO  ┆ 9643       ┆ … ┆ null       ┆ 2.0501e10  ┆ ZULEIDE   ┆ 650,00    │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
 │            ┆            ┆     ┆            ┆   ┆            ┆            ┆ E SILVA   ┆           │
 └────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘}

In [18]:
df_bolsapl.columns

['mes_competencia',
 'mes_referencia',
 'uf',
 'cod_municipio_siafi',
 'nome_municipio',
 'cpf_favorecido',
 'nis_favorecido',
 'nome_favorecido',
 'valor_parcela']

In [ ]:
#conversão dos nomes das colunas:

df_bolsapl = df_bolsapl.rename({
    "MÊS COMPETÊNCIA": "mes_competencia",
    "MÊS REFERÊNCIA": "mes_referencia",
    "UF": "uf",
    "CÓDIGO MUNICÍPIO SIAFI": "cod_municipio_siafi",
    "NOME MUNICÍPIO": "nome_municipio",
    "CPF FAVORECIDO": "cpf_favorecido",
    "NIS FAVORECIDO": "nis_favorecido",
    "NOME FAVORECIDO": "nome_favorecido",
    "VALOR PARCELA": "valor_parcela"
})

In [36]:
df_bolsapl.head(10)

shape: (10, 8)
┌─────────────┬─────────────┬─────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ mes_compete ┆ mes_referen ┆ uf  ┆ cod_munici ┆ nome_munic ┆ nis_favore ┆ nome_favor ┆ valor_parc │
│ ncia        ┆ cia         ┆ --- ┆ pio_siafi  ┆ ipio       ┆ cido       ┆ ecido      ┆ ela        │
│ ---         ┆ ---         ┆ str ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64         ┆ i64         ┆     ┆ i64        ┆ str        ┆ str        ┆ str        ┆ f64        │
╞═════════════╪═════════════╪═════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 202501      ┆ 202308      ┆ SP  ┆ 7071       ┆ santos     ┆ 2064389044 ┆ FERNANDA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆            ┆ 5          ┆ RAMOS      ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ TEIXEIRA   ┆            │
│ 202501      ┆ 202309      ┆ SP  ┆ 7071       ┆ santos     ┆ 2064389044 ┆ FERNANDA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆            ┆ 5          ┆ RAMOS      ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ TEIXEIRA   ┆            │
│ 202501      ┆ 202310      ┆ SP  ┆ 7071       ┆ santos     ┆ 2064389044 ┆ FERNANDA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆            ┆ 5          ┆ RAMOS      ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ TEIXEIRA   ┆            │
│ 202501      ┆ 202311      ┆ SP  ┆ 7071       ┆ santos     ┆ 2064389044 ┆ FERNANDA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆            ┆ 5          ┆ RAMOS      ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ TEIXEIRA   ┆            │
│ 202501      ┆ 202312      ┆ SP  ┆ 7071       ┆ santos     ┆ 2064389044 ┆ FERNANDA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆            ┆ 5          ┆ RAMOS      ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ TEIXEIRA   ┆            │
│ 202501      ┆ 202401      ┆ CE  ┆ 1389       ┆ fortaleza  ┆ 1302405519 ┆ IRENICE    ┆ 750.0      │
│             ┆             ┆     ┆            ┆            ┆ 2          ┆ CAMELO     ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ VALETE     ┆            │
│ 202501      ┆ 202401      ┆ PA  ┆ 479        ┆ limoeiro   ┆ 1602513240 ┆ ANTONIA    ┆ 600.0      │
│             ┆             ┆     ┆            ┆ do ajuru   ┆ 3          ┆ ELIZANA DA ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ SILVA      ┆            │
│ 202501      ┆ 202401      ┆ SP  ┆ 6313       ┆ carapicuib ┆ 1331023985 ┆ DAMARIS    ┆ 800.0      │
│             ┆             ┆     ┆            ┆ a          ┆ 2          ┆ DOS SANTOS ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ OLIVEIRA   ┆            │
│ 202501      ┆ 202401      ┆ SP  ┆ 6313       ┆ carapicuib ┆ 2021744274 ┆ PRISCILA   ┆ 650.0      │
│             ┆             ┆     ┆            ┆ a          ┆ 3          ┆ HELENA DE  ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ LIMA       ┆            │
│ 202501      ┆ 202401      ┆ SP  ┆ 6887       ┆ pirassunun ┆ 1601742565 ┆ ERICA      ┆ 1010.0     │
│             ┆             ┆     ┆            ┆ ga         ┆ 0          ┆ CRISTINA   ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ RIBEIRO DA ┆            │
│             ┆             ┆     ┆            ┆            ┆            ┆ SILV…      ┆            │
└─────────────┴─────────────┴─────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
#conversão da coluna de valor para numero com . ao invés de ,

df_bolsapl = df_bolsapl.with_columns([
    pl.col("valor_parcela")
    .str.replace(",", ".")
    .cast(pl.Float64)
    .alias("valor_parcela")
])

df_bolsapl.select("valor_parcela").head(10)

shape: (10, 1)
┌───────────────┐
│ valor_parcela │
│ ---           │
│ f64           │
╞═══════════════╡
│ 650.0         │
│ 650.0         │
│ 650.0         │
│ 650.0         │
│ 650.0         │
│ 750.0         │
│ 600.0         │
│ 800.0         │
│ 650.0         │
│ 1010.0        │
└───────────────┘

In [21]:
df_bolsapl.null_count()

shape: (1, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ mes_compet ┆ mes_refere ┆ uf  ┆ cod_munici ┆ … ┆ cpf_favore ┆ nis_favore ┆ nome_favo ┆ valor_par │
│ encia      ┆ ncia       ┆ --- ┆ pio_siafi  ┆   ┆ cido       ┆ cido       ┆ recido    ┆ cela      │
│ ---        ┆ ---        ┆ u32 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆ u32        ┆     ┆ u32        ┆   ┆ u32        ┆ u32        ┆ u32       ┆ u32       │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 0          ┆ 0   ┆ 0          ┆ … ┆ 7942467    ┆ 725        ┆ 0         ┆ 0         │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [ ]:
#descarte da coluna CPF que tem muitos valores nulos

df_bolsapl = df_bolsapl.drop("cpf_favorecido")

In [23]:
#comparação das colunas de mês que podem estar redundantes:

(df_bolsapl.select([
    (pl.col("mes_competencia") != pl.col("mes_referencia")).alias("diferente")
])
.filter(pl.col("diferente") == True)
).height

193687

In [28]:
#normalizar nomes retirando acentos e espaços para não atrapalhar análises

import unidecode

# função auxiliar para remover acentos:

def normalizar_texto(s):
    if s is not None:
        return unidecode.unidecode(s.strip().lower())
    return s

# aplicar no nome do município:

df_bolsapl = df_bolsapl.with_columns([
    pl.col("nome_municipio").map_elements(normalizar_texto).alias("nome_municipio")
])

C:\Users\Win\AppData\Local\Temp\ipykernel_20956\3950830719.py:14: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  df_bolsapl = df_bolsapl.with_columns([

In [ ]:
#garante que a coluna esteja no formato str ao invés de f64: 

df_bolsapl = df_bolsapl.with_columns([
    pl.col("nis_favorecido").cast(pl.Utf8).alias("nis_favorecido")
])

In [ ]:
#verificando se existe algum valor não inteiro (que não seja x.0) na coluna:

df_bolsapl.select(
    (pl.col("nis_favorecido")
    .cast(pl.Float64) % 1 != 0)
    .sum()
    .alias("nis_nao_inteiros")
)

shape: (1, 1)
┌──────────────────┐
│ nis_nao_inteiros │
│ ---              │
│ u32              │
╞══════════════════╡
│ 0                │
└──────────────────┘

In [35]:
df_bolsapl = df_bolsapl.with_columns([
    pl.col("nis_favorecido")
    .cast(pl.Utf8)
    .str.replace(r"\.0$", "")
    .alias("nis_favorecido")
])